### PR TITLE
optimize(api): add warning logs for load-based request rejection

### LINKED ISSUE #2747: [Improvement] Add critical log statements.
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: master

### Expected & Actual behavior (期望与实际表现)

Add critical log statements.
LoadDetectFilter.java #filter 
...
throw new ServiceUnavailableException
...
When certain conditions are met, an exception is thrown and directly returned to the client, while the server does not log this exception

### Vertex/Edge example (问题点 / 边数据举例)

```javascript

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript

```

### PR DESCRIPTION
**Pull request by contrueCT**
## Purpose of the PR

- close #2747  

## Main Changes

Log busy-worker and low-memory rejections in LoadDetectFilter before returning ServiceUnavailableException so operators can diagnose 503 responses from server-side logs.

Add unit coverage for whitelist bypass, busy rejection,
low-memory rejection, and healthy request pass-through, and register the new test in UnitTestSuite.

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
    - xxx

## Does this PR potentially affect the following parts?

- [ ]  Dependencies ([add/update license](https://hugegraph.apache.org/docs/contribution-guidelines/contribute/#321-check-licenses) info & [regenerate_known_dependencies.sh](../install-dist/scripts/dependency/regenerate_known_dependencies.sh)) 
- [ ]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)
- [ ]  Nope

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [ ]  `Doc - No Need`

### CODE REVIEW

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 1]
```diff
@@ -84,6 +107,10 @@ public void filter(ContainerRequestContext context) {
                                   allocatedMem) / Bytes.MB;
         if (presumableFreeMem < minFreeMemory) {
             gcIfNeeded();
+            LOG.warn("Rejected request due to low free memory, method={}, path={}, " +
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java]: ⚠️ 这里先 `gcIfNeeded()` 再记录日志，但当前日志里的 `presumableFreeMem` 是 GC 前快照。排障时容易误解为“GC 后仍然是这个值”。

建议同时输出 GC 前/后快照，定位会更直观：

```suggestion
gcIfNeeded();
long allocatedMemAfterGc = Runtime.getRuntime().totalMemory() -
                           Runtime.getRuntime().freeMemory();
long freeMemAfterGc = (Runtime.getRuntime().maxMemory() -
                       allocatedMemAfterGc) / Bytes.MB;
LOG.warn("Rejected request due to low free memory, method={}, path={}, " +
         "presumableFreeMemMB(beforeGC)={}, presumableFreeMemMB(afterGC)={}, minFreeMemoryMB={}",
         context.getMethod(), context.getUriInfo().getPath(),
         presumableFreeMem, freeMemAfterGc, minFreeMemory);
```

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 2]
```diff
@@ -70,7 +88,12 @@ public void filter(ContainerRequestContext context) {
         int maxWorkerThreads = config.get(ServerOptions.MAX_WORKER_THREADS);
         WorkLoad load = this.loadProvider.get();
         // There will be a thread doesn't work, dedicated to statistics
-        if (load.incrementAndGet() >= maxWorkerThreads) {
+        int currentLoad = load.incrementAndGet();
+        if (currentLoad >= maxWorkerThreads) {
+            LOG.warn("Rejected request due to high worker load, method={}, path={}, " +
+                     "currentLoad={}, maxWorkerThreads={}",
+                     context.getMethod(), context.getUriInfo().getPath(),
+                     currentLoad, maxWorkerThreads);
```
[the remark this answers is not in the document]
Comment (imbajin) [reply hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java]: > The new WARN logs will be emitted for every rejected request; under overload this can produce a log storm and further degrade the server (I/O, disk, log rotation). Consider rate-limiting/sampling these rejection logs (similar to the existing RateLimiter usage elsewhere) or logging once per interval with aggregated counters.

⚠️ 每次请求都会打印 `WARN`，可能产生大量日志 I/O，进一步放大系统抖动（导入/批量写入期间更明显）。

可以给“拒绝日志”加一个轻量限速（只限日志，不限请求处理），这样不会阻塞线程：

```suggestion
if (REJECT_LOG_RATE_LIMITER.tryAcquire()) {
    LOG.warn("Rejected request due to high worker load, method={}, path={}, " +
             "currentLoad={}, maxWorkerThreads={}",
             context.getMethod(), context.getUriInfo().getPath(),
             currentLoad, maxWorkerThreads);
}
```

// 每秒最多 1 条日志记录
参考：`private static final RateLimiter REJECT_LOG_RATE_LIMITER = RateLimiter.create(1.0);`

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 3]
```diff
@@ -70,7 +93,14 @@ public void filter(ContainerRequestContext context) {
         int maxWorkerThreads = config.get(ServerOptions.MAX_WORKER_THREADS);
         WorkLoad load = this.loadProvider.get();
         // There will be a thread doesn't work, dedicated to statistics
-        if (load.incrementAndGet() >= maxWorkerThreads) {
+        int currentLoad = load.incrementAndGet();
+        if (currentLoad >= maxWorkerThreads) {
+            if (REJECT_LOG_RATE_LIMITER.tryAcquire()) {
+                LOG.warn("Rejected request due to high worker load, method={}, path={}, " +
+                         "currentLoad={}, maxWorkerThreads={}",
+                         context.getMethod(), context.getUriInfo().getPath(),
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java:118]: ⚠️ The busy-load branch is rate-limited, but this low-memory WARN will still fire on every rejected request. Under sustained memory pressure that can flood the logs and add more I/O pressure to an already stressed server. Please apply the same `REJECT_LOG_RATE_LIMITER` here, or route both rejection logs through a shared sampling helper.

```suggestion
if (REJECT_LOG_RATE_LIMITER.tryAcquire()) {
    LOG.warn("Rejected request due to low free memory, method={}, path={}, " +
             "presumableFreeMemMB={}, recheckedFreeMemMB={}, gcTriggered={}, " +
             "minFreeMemoryMB={}",
             context.getMethod(), context.getUriInfo().getPath(),
             presumableFreeMem, recheckedFreeMem, gcTriggered,
             minFreeMemory);
}
```

File: hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/api/filter/LoadDetectFilterTest.java [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+
+        ServiceUnavailableException exception = (ServiceUnavailableException) Assert.assertThrows(
+                ServiceUnavailableException.class,
+                () -> this.loadDetectFilter.filter(this.requestContext));
+
+        Assert.assertContains("The server is too busy to process the request",
+                              exception.getMessage());
+        Assert.assertContains(ServerOptions.MAX_WORKER_THREADS.name(),
+                              exception.getMessage());
+    }
```
Comment (imbajin) [inline hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/api/filter/LoadDetectFilterTest.java:135]: ⚠️ This test drives the real `System.gc()` path by forcing the low-memory branch. That makes the suite slower and can make it behave differently on constrained CI nodes or JVMs with different GC ergonomics. Consider adding a test seam for the GC step so the test can stub it and only verify the rejection behavior.

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 5]
```diff
@@ -83,7 +113,17 @@ public void filter(ContainerRequestContext context) {
         long presumableFreeMem = (Runtime.getRuntime().maxMemory() -
                                   allocatedMem) / Bytes.MB;
         if (presumableFreeMem < minFreeMemory) {
-            gcIfNeeded();
+            boolean gcTriggered = gcIfNeeded();
+            long allocatedMemAfterCheck = Runtime.getRuntime().totalMemory() -
+                                          Runtime.getRuntime().freeMemory();
+            long recheckedFreeMem = (Runtime.getRuntime().maxMemory() -
+                                     allocatedMemAfterCheck) / Bytes.MB;
+            LOG.warn("Rejected request due to low free memory, method={}, path={}, " +
```
Comment (VGalaxies) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java]: Please rate-limit the low-memory rejection log too. Logging every 503 in a memory-pressure path can amplify the problem, while the worker-load branch already uses a limiter for the same reason.

File: hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/api/filter/LoadDetectFilterTest.java [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+
+    @Test
+    public void testFilter_RejectsWhenFreeMemoryIsTooLow() {
+        setupPath("graphs/hugegraph/vertices",
+                  List.of("graphs", "hugegraph", "vertices"));
+        this.setConfigProvider(createConfig(8, Integer.MAX_VALUE));
+
+        ServiceUnavailableException exception = (ServiceUnavailableException) Assert.assertThrows(
```
Comment (VGalaxies) [inline hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/api/filter/LoadDetectFilterTest.java:145]: These tests only re-check the 503 exception message; they do not cover the new logging behavior. Please add at least one test that validates the warning log is emitted, and ideally one that covers rate-limiting behavior as well.

**Review by VGalaxies — COMMENTED** [review]
Thanks for the update. I left two small review comments; CI looks green on my side, but I think these are still worth addressing.

**Comment by contrueCT** [comment]
> Thanks for the update. I left two small review comments; CI looks green on my side, but I think these are still worth addressing.

> ⚠️ The busy-load branch is rate-limited, but this low-memory WARN will still fire on every rejected request. Under sustained memory pressure that can flood the logs and add more I/O pressure to an already stressed server. Please apply the same REJECT_LOG_RATE_LIMITER here, or route both rejection logs through a shared sampling helper.
> ⚠️ This test drives the real System.gc() path by forcing the low-memory branch. That makes the suite slower and can make it behave differently on constrained CI nodes or JVMs with different GC ergonomics. Consider adding a test seam for the GC step so the test can stub it and only verify the rejection behavior.



Changes made:
- Applied the same reject-log rate limiting to the low-memory branch, and routed both rejection paths through a shared warning helper so the sampling behavior is consistent.
- Added a small test seam for `gcIfNeeded()` / reject-log sampling so the unit test no longer depends on a real `System.gc()` call.
- Expanded `LoadDetectFilterTest` to verify:
  - busy rejection emits a warning log
  - low-memory rejection emits a warning log
  - whitelist / healthy paths do not emit rejection logs
  - reject-log sampling suppresses repeated warning logs as expected

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 7]
```diff
@@ -83,7 +121,20 @@ public void filter(ContainerRequestContext context) {
...
+            boolean gcTriggered = this.gcIfNeeded();
+            if (shouldLog) {
+                long allocatedMemAfterCheck = Runtime.getRuntime().totalMemory() -
+                                              Runtime.getRuntime().freeMemory();
+                long recheckedFreeMem = (Runtime.getRuntime().maxMemory() -
+                                         allocatedMemAfterCheck) / Bytes.MB;
+                LOG.warn("Rejected request due to low free memory, method={}, path={}, " +
+                         "presumableFreeMemMB={}, recheckedFreeMemMB={}, gcTriggered={}, " +
+                         "minFreeMemoryMB={}",
+                         context.getMethod(), context.getUriInfo().getPath(),
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java:154]: ‼️ **内存拒绝路径中的逻辑问题：GC 后未重新检查内存**

当前逻辑在 GC 后直接抛出异常，并没有重新检查内存是否已恢复到阈值以上。既然已经在这里做了 `recheckedFreeMem` 计算，建议更进一步：**GC 后重新检查内存，如果已恢复则放行请求**，减少不必要的 503。

当前行为：检测到内存不足 → 尝试 GC → 记录 GC 后的内存 → **仍然抛异常**
建议行为：检测到内存不足 → 尝试 GC → 重新检查 → 如果恢复则放行

```suggestion
            boolean gcTriggered = this.gcIfNeeded();
            if (gcTriggered) {
                long allocatedMemAfterGc = Runtime.getRuntime().totalMemory() -
                                           Runtime.getRuntime().freeMemory();
                long freeMemAfterGc = (Runtime.getRuntime().maxMemory() -
                                       allocatedMemAfterGc) / Bytes.MB;
                if (freeMemAfterGc >= minFreeMemory) {
                    this.logRejectWarning(
                            "Low memory recovered after GC, method={}, path={}, " +
                            "beforeFreeMB={}, afterFreeMB={}",
                            context.getMethod(), context.getUriInfo().getPath(),
                            presumableFreeMem, freeMemAfterGc);
                    return;
                }
            }
            this.logRejectWarning(
                    "Rejected request due to low free memory, method={}, path={}, " +
                    "presumableFreeMemMB={}, gcTriggered={}, minFreeMemoryMB={}",
                    context.getMethod(), context.getUriInfo().getPath(),
                    presumableFreeMem, gcTriggered, minFreeMemory);
```

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 8]
```diff
@@ -54,11 +58,40 @@ public class LoadDetectFilter implements ContainerRequestFilter {
...
     @Context
     private jakarta.inject.Provider<HugeConfig> configProvider;
     @Context
     private jakarta.inject.Provider<WorkLoad> loadProvider;
 
+    public static boolean isWhiteAPI(ContainerRequestContext context) {
+        List<PathSegment> segments = context.getUriInfo().getPathSegments();
+        E.checkArgument(!segments.isEmpty(), "Invalid request uri '%s'",
+                        context.getUriInfo().getPath());
+        String rootPath = segments.get(0).getPath();
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java:84]: ⚠️ **方法可见性变更：`gcIfNeeded` 从 `private static` 改为 `protected` 实例方法**

原方法是 `private static void gcIfNeeded()`，现改为 `protected boolean gcIfNeeded()`。变更影响：
1. 扩大可见性（private → protected），破坏了封装性
2. 从静态方法变为实例方法
3. 主要目的似乎是为了测试时 override

建议保持 `private` 可见性，如果需要测试可测试性，可以：
- 使用 package-private 可见性 + `@VisibleForTesting` 注解
- 或者通过注入策略接口实现

同样的建议也适用于 `allowRejectLog()` 方法。

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 9]
```diff
@@ -54,11 +58,40 @@ public class LoadDetectFilter implements ContainerRequestFilter {
     private static final RateLimiter GC_RATE_LIMITER =
             RateLimiter.create(1.0 / 30);
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java:62]: ⚠️ **两条拒绝路径共享同一个 `REJECT_LOG_RATE_LIMITER`**

高负载拒绝和低内存拒绝共享同一个 RateLimiter（每秒 1 个 permit）。这意味着：
- 如果高负载拒绝消耗了 permit，紧接着的低内存拒绝就不会被记录（反之亦然）
- 运维人员在同时出现高负载和低内存时，可能只看到一种告警，遗漏另一种

建议为两种拒绝原因使用独立的 RateLimiter：
```java
private static final RateLimiter BUSY_LOG_LIMITER = RateLimiter.create(1.0);
private static final RateLimiter MEMORY_LOG_LIMITER = RateLimiter.create(1.0);
```

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 10]
```diff
@@ -54,11 +58,40 @@ public class LoadDetectFilter implements ContainerRequestFilter {
...
+            return true;
+        }
+        return false;
+    }
+
+    protected boolean allowRejectLog() {
+        return REJECT_LOG_RATE_LIMITER.tryAcquire();
+    }
+
+    protected void logRejectWarning(String message, Object... args) {
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java]: ⚠️ **`logRejectWarning()` 与直接调用 `allowRejectLog()` 的不一致**

高负载路径使用封装的 `logRejectWarning()`，但低内存路径直接调用 `allowRejectLog()` + `LOG.warn()`：

```java
// 高负载路径
this.logRejectWarning("Rejected request due to high worker load...");

// 低内存路径
boolean shouldLog = this.allowRejectLog();
if (shouldLog) { LOG.warn(...); }
```

两条路径的日志方式不一致，降低了可读性。建议统一为同一种模式。另外 `logRejectWarning()` 在生产代码中只被调用了一次，是否真的需要抽取为独立方法值得考虑。

File: hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java [hunk 11]
```diff
@@ -83,7 +121,20 @@ public void filter(ContainerRequestContext context) {
         long presumableFreeMem = (Runtime.getRuntime().maxMemory() -
                                   allocatedMem) / Bytes.MB;
         if (presumableFreeMem < minFreeMemory) {
-            gcIfNeeded();
+            boolean shouldLog = this.allowRejectLog();
+            boolean gcTriggered = this.gcIfNeeded();
+            if (shouldLog) {
+                long allocatedMemAfterCheck = Runtime.getRuntime().totalMemory() -
```
Comment (imbajin) [inline hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/LoadDetectFilter.java]: 🧹 **`recheckedFreeMem` 在 `gcTriggered=false` 时是冗余信息**

当 `gcTriggered=false` 时，`recheckedFreeMem` 和 `presumableFreeMem` 几乎完全相同（两次采样之间几乎没有时间差），日志中两个近似相同的值会造成困惑。

建议只在 `gcTriggered=true` 时才计算并记录 `recheckedFreeMem`，否则省略此字段。

**Review by imbajin — APPROVED** [review]
Good enhancement
