### PR TITLE
refact(server): enlarge bytes write limit & remove param `big` when encode/decode string id length

### LINKED ISSUE #1593: [Question] hugegraph-loader导入数据报错PARSE ERROR: Vertex id length limit is '128'
### Problem Type (问题类型)

_No response_

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: hugegraph-loader-0.9.0、hugegraph-0.9.2
- Backend: cassandra
- OS: 16 CPUs, 64 G RAM, Centos 7.x 
- Data Size:  74262950 vertices, 37131475 edges 

### Your Question (问题描述)

使用hugegraph-loader导入数据报错，后端存储使用cassandra存储，应该调整什么参数呢
PARSE ERROR: Vertex id length limit is '128'

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by VGalaxies**
As title, change limit:
- vid max to 16KB
- eid max to 64kb (128k as backup)
- property max to 10MB (keep consistent)

fix #1593 #2291

### CODE REVIEW

File: hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BytesBuffer.java [hunk 1]
```diff
@@ -288,10 +295,10 @@ public double readDouble() {
     }
 
     public BytesBuffer writeBytes(byte[] bytes) {
-        E.checkArgument(bytes.length <= UINT16_MAX,
+        E.checkArgument(bytes.length <= BYTES_LEN_MAX,
```
Comment (imbajin) [inline hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BytesBuffer.java:298]: `int32 <== int32`?

File: hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/structure/HugeEdge.java [hunk 2]
```diff
@@ -147,9 +147,9 @@ public void assignId() {
 
         if (this.fresh()) {
             int len = this.id.length();
-            E.checkArgument(len <= BytesBuffer.BIG_ID_LEN_MAX,
+            E.checkArgument(len <= BytesBuffer.ID_LEN_MAX,
                             "The max length of edge id is %s, but got %s {%s}",
-                            BytesBuffer.BIG_ID_LEN_MAX, len, this.id);
+                            BytesBuffer.ID_LEN_MAX, len, this.id);
```
Comment (imbajin) [inline hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/structure/HugeEdge.java:152]: correct? when `vid <= ID_LEN_MAX`

**Review by imbajin — DISMISSED** [review]
THX~

**Review by JackyYangPassion — APPROVED** [review]

**Review by imbajin — APPROVED** [review]
