### PR TITLE
Fix bug: Closing iterators on errors for CassandraTable and MysqlTable

### LINKED ISSUE #1983: [Bug] should close ExtendableIterator when cassandra exception
### Bug Type (问题类型)

logic (逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

`ExtendableIterator<R> rs` should be closed when an exception is encountered:
https://github.com/apache/incubator-hugegraph/blob/b699c5cd621ac91e53c08320c17902f401d3a391/hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java#L156

### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by vamossagar12**
Fix #1983

### CODE REVIEW

**Comment by vamossagar12** [comment]
hi @javeme . Plz review. I noticed a similar issue for MysqlTable so added that as well as part of the PR

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java [hunk 1]
```diff
@@ -156,6 +156,12 @@ protected <R> Iterator<R> query(Query query,
         } catch (DriverException e) {
             LOG.debug("Failed to query [{}], detail statement: {}",
                       query, selects, e);
+            // Closing the iterator
+            try {
+                rs.close();
+            } catch (Exception closeException) {
+                throw new BackendException("Error closing Iterator during query [%s]", e, query);
```
Comment (javeme) [inline hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java:163]: I think it's better to just log.error closeException here and let throw the DriverException at line 165, because closeException is not the main path.

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java [hunk 2]
```diff
@@ -477,6 +477,12 @@ protected <R> Iterator<R> query(Session session, Query query,
                 rs.extend(parser.apply(query, results));
             }
         } catch (SQLException e) {
+            // closing iterator
+            try {
+                rs.close();
+            } catch (Exception closeException) {
+                throw new BackendException("Error closing Iterator during query [%s]", e, query);
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java:484]: ditto

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java [hunk 3]
```diff
@@ -156,6 +156,12 @@ protected <R> Iterator<R> query(Query query,
         } catch (DriverException e) {
             LOG.debug("Failed to query [{}], detail statement: {}",
                       query, selects, e);
+            // Closing the iterator
+            try {
+                rs.close();
+            } catch (Exception closeException) {
```
Comment (javeme) [inline hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java:162]: 'e2' name is ok

**Review by javeme — COMMENTED** [review]
Thanks for your contribution

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java (hunk 1 above)
Comment (vamossagar12) [reply hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java]: done

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java (hunk 2 above)
Comment (vamossagar12) [reply hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java]: done

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java (hunk 3 above)
Comment (vamossagar12) [reply hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java]: done

**Comment by vamossagar12** [comment]
> Thanks for your contribution

Thanks @javeme . I made the changes.

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java [hunk 4]
```diff
@@ -156,6 +156,12 @@ protected <R> Iterator<R> query(Query query,
         } catch (DriverException e) {
             LOG.debug("Failed to query [{}], detail statement: {}",
                       query, selects, e);
+            // Closing the iterator
+            try {
+                rs.close();
+            } catch (Exception e2) {
+                LOG.error("Got error {} when closing iterator for query {}", e, query);
```
Comment (javeme) [inline hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java:163]: I think we should log e2 here

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java [hunk 5]
```diff
@@ -477,6 +477,12 @@ protected <R> Iterator<R> query(Session session, Query query,
                 rs.extend(parser.apply(query, results));
             }
         } catch (SQLException e) {
+            // Closing the iterator
+            try {
+                rs.close();
+            } catch (Exception e2) {
+                LOG.error("Got error {} when closing iterator for query {}", e, query);
```
Comment (javeme) [inline hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java:484]: ditto

File: hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java (hunk 4 above)
Comment (vamossagar12) [reply hugegraph-cassandra/src/main/java/com/baidu/hugegraph/backend/store/cassandra/CassandraTable.java]: sorry about that. Fixed it.

File: hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java (hunk 5 above)
Comment (vamossagar12) [reply hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTable.java]: fixed.

**Review by imbajin — APPROVED** [review]

**Review by javeme — APPROVED** [review]
