### PR TITLE
fix: format and clean code in core module

### LINKED ISSUE #2435: [Summary] Enhance code style warnings in server
### SubTask

**PS: One PR for multiple modules is fine, but if the total code exceeds **4000** lines, split it into multiple PRs.**

- [x] Adhere to the code conventions outlined in [HugeGraph-Code-Style-Guide](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide) (please refine the hg-style.xml specification @returnToInnocence) https://github.com/apache/incubator-hugegraph/pull/2457
   - [x] Add the option 'BLANK_LINES_AFTER_CLASS_HEADER' 
   - [x] Add the option 'KEEP_BLANK_LINES'
   - [x] ....
- [x] Correct the copyright format.
	- [x] #2438
	- [x] #2445
- [x] Format the server module 
   - [x] hugegraph-api & cassandra & palo & postgresql & rocksdb & scylladb & test & hbase & mysql (wip #2439)
   - [x] hugegraph-core #2440
   - [x] hugegraph-dist & example #2441
   - [x]  remove extra blank lines https://github.com/apache/incubator-hugegraph/pull/2459
- [x] clean up the code. https://github.com/apache/incubator-hugegraph/pull/2456
- [x] Doc [hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg](https://hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg)@returnToInnocence
	- [x] Provide doc on how to retain/install multiple versions of IntelliJ IDE 
	- [x] Unified IDE Rules Setup Tutorial 

### Expected & Actual behavior (期望与实际表现)

image
image
image

### TODO
- [ ] IDEA formatting plugin currently lacks support for adding a blank line after enum declarations.image
- [ ] Use [spotless](https://github.com/diffplug/spotless) to format code

### PR DESCRIPTION
**Pull request by msgui**
## Purpose of the PR
- subtask of #2435

## Main Changes

Format & clean code in submodels:

1. Core

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
  - xxx

## Does this PR potentially affect the following parts?

- [ ] Nope
- [ ] Dependencies (add/update license info) 
- [ ] Modify configurations
- [ ] The public API
- [ ] Other affects (typed here)

## Documentation Status

- [ ] `Doc - TODO` 
- [ ] `Doc - Done` 
- [ ] `Doc - No Need`

### CODE REVIEW

File: hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/StandardHugeGraph.java [hunk 1]
```diff
@@ -121,26 +121,26 @@
...
-        StandardHugeGraph.class,
-        StandardHugeGraph.StandardHugeGraphParams.class,
-        TinkerPopTransaction.class,
-        StandardHugeGraph.Txs.class,
-        StandardHugeGraph.SysTransaction.class
+            StandardHugeGraph.class,
+            StandardHugeGraph.StandardHugeGraphParams.class,
+            TinkerPopTransaction.class,
+            StandardHugeGraph.Txs.class,
+            StandardHugeGraph.SysTransaction.class
```
Comment (imbajin) [inline hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/StandardHugeGraph.java:128]: **IMPORTANT:** we need to ensure 4 or 8 spaces to format (and sync to "hugegraph-style" **config files** & other PRs)

**Review by imbajin — APPROVED** [review]
Check Most of the files have been checked

**Review by VGalaxies — APPROVED** [review]
