### PR TITLE
fix: transfer add_peer/remove_peer command to leader

### LINKED ISSUE #2111: [Bug] raft模式add_peer失败
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v1.0.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

期望raft命令可正常执行

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
使用raft模式，在leader上add_peer的时候，执行完raft-tools的命令之后，发现报错：
java.lang.IllegalArgumentException: Operation add_peer can only be executed on leader


猜测：执行raft操作后，hg会生成一个异步任务，这个任务可能会调度到其他节点上，导致该报错。之前版本应该不会生成异步任务，也就不会有这个报错
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

### PR DESCRIPTION
**Pull request by simon824**
fixed #2111
### Environment
<table>
<tr>
	<td>
	<td>127.0.0.1:9001
	<td>127.0.0.1:9002
	<td>127.0.0.1:9003
<tr>
	<td>server.role
	<td>master
	<td>worker
	<td>worker
<tr>
	<td>raft.role
	<td>replicator
	<td>leader
	<td>replicator
</table>

### 1. list all peers
image
### 2. add peer 127.0.0.1:9003
image
### 3. check async task
image
### 4. list all peers again
image

### CODE REVIEW

File: hugegraph-core/src/main/java/org/apache/hugegraph/backend/store/raft/RaftGroupManagerImpl.java [hunk 1]
```diff
@@ -133,16 +143,20 @@ public String addPeer(String endpoint) {
...
         PeerId peerId = PeerId.parsePeer(endpoint);
-        RaftClosure<?> future = new RaftClosure<>();
         try {
-            this.raftNode.node().removePeer(peerId, future);
+            RaftClosure<?> future = new RaftClosure<>();
+            if (this.raftNode.selfIsLeader()) {
+                this.raftNode.node().removePeer(peerId, future);
+            } else {
+                RemovePeerRequest request = RemovePeerRequest.newBuilder()
+                    .setEndpoint(endpoint)
```
Comment (javeme) [inline hugegraph-core/src/main/java/org/apache/hugegraph/backend/store/raft/RaftGroupManagerImpl.java:153]: prefer to align with `.newBuilder`

**Review by javeme — DISMISSED** [review]

**Review by javeme — APPROVED** [review]

**Review by zyxxoo — APPROVED** [review]
