### PR TITLE
fix(pd): populate memberSize in GET / endpoint response

### LINKED ISSUE #3002: [Bug] GET / endpoint always returns memberSize:0 regardless of actual PD member count
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.7.0 (latest Docker image)
- Backend: hstore 3 nodes
- OS: macOS (Apple M4), Docker Desktop
- Data Size: N/A — reproducible on fresh cluster

### Expected & Actual behavior (期望与实际表现)

The `memberSize` field in the response from `GET /` (IndexAPI) always returns 0 
regardless of how many PD nodes are actually in the cluster.

Actual:
curl -u store:store http://localhost:8620/
{"state":"Cluster_Not_Ready","leader":"pd2:8686","memberSize":0,"storeSize":3,...}

Expected:
memberSize should return 3 for a 3-node PD cluster.

Root cause:
IndexAPI.index() sets storeSize, graphSize, partitionSize, leader but never 
sets memberSize on the BriefStatistics object. The field defaults to 0.

The /v1/cluster endpoint in the same file does it correctly:
statistics.memberSize = pdList.size();

Fix: add the equivalent line in index() using 
RaftEngine.getInstance().getMembers().size()

### PR DESCRIPTION
**Pull request by caglareker**
## Purpose of the PR
- fix #3002

## Main Changes
The `memberSize` field in `BriefStatistics` was never being set, so GET / always returned 0. Added the missing assignment from `RaftEngine.getInstance().getMembers().size()`, same pattern as the other fields right next to it.

## Verifying these changes
- [x] trivial change
- [ ] already covered by existing tests
- [ ] needs new tests

### CODE REVIEW

**Review by bitflicker64 — APPROVED** [review]
Tested locally with Docker dev cluster , memberSize now returns 1 (was 0). LGTM

**Comment by caglareker** [comment]
Thanks for testing it out, glad it works.

**Comment by imbajin** [comment]
> Tested locally with Docker dev cluster , memberSize now returns 1 (was 0). LGTM

maybe we need test again for the new logic
https://github.com/apache/hugegraph/pull/3003/commits/4db9735bd5fcd2de8714d85e55515b0d62aea675

File: hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/rest/IndexAPI.java [hunk 1]
```diff
@@ -66,9 +66,35 @@ public BriefStatistics index() throws PDException, ExecutionException, Interrupt
...
         statistics.state = pdService.getStoreNodeService().getClusterStats().getState().toString();
+
+        // Use pdService (consistent with cluster()) rather than RaftEngine directly
+        CallStreamObserverWrap<Pdpb.GetMembersResponse> membersResp =
+                new CallStreamObserverWrap<>();
+        pdService.getMembers(Pdpb.GetMembersRequest.newBuilder().build(), membersResp);
+        statistics.memberSize = membersResp.get().get(0).getMembersList().size();
+
         statistics.storeSize = pdService.getStoreNodeService().getActiveStores().size();
-        statistics.graphSize = pdService.getPartitionService().getGraphs().size();
```
Comment (imbajin) [inline hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/rest/IndexAPI.java:70]: The previous fix adds:
`statistics.memberSize = RaftEngine.getInstance().getMembers().size();`

But the cluster() method (the "correct" counterpart) uses the service layer:
```java
pdService.getMembers(Pdpb.GetMembersRequest.newBuilder().build(), response);
statistics.memberSize = pdList.size();  // from pdService, not RaftEngine
```

The issue discussion (comments 3–4 from bitflicker64 and dosubot) explicitly recommends using pdService.getMembers().size() for consistency with cluster() and to stay in the service layer. The merged fix goes against this recommendation.

**Comment by bitflicker64** [comment]
> > Tested locally with Docker dev cluster , memberSize now returns 1 (was 0). LGTM
> 
> maybe we need test again for the new logic [4db9735](https://github.com/apache/hugegraph/commit/4db9735bd5fcd2de8714d85e55515b0d62aea675)

Re-tested locally against commit 4db9735 , all fields return correctly: memberSize: 1, storeSize: 1, dataState: PState_Normal.

**Review by imbajin — APPROVED** [review]
